"""create all tables

Revision ID: 0b7a54c747ce
Revises: 
Create Date: 2026-05-22 00:26:20.132214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7a54c747ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengguna',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Operator', 'Viewer', name='roleenum'), nullable=False),
    sa.Column('status', sa.Enum('Aktif', 'Nonaktif', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wilayah',
    sa.Column('wilayah_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_wilayah', sa.String(length=100), nullable=False),
    sa.Column('tingkat', sa.Enum('Kecamatan', 'Kelurahan', name='tingkatenum'), nullable=False),
    sa.Column('kota', sa.String(length=50), nullable=False),
    sa.Column('provinsi', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('wilayah_id')
    )
    op.create_table('log_sinkronisasi',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('waktu_sinkronisasi', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('Berhasil', 'Gagal', 'Sebagian', name='statuslogenum'), nullable=False),
    sa.Column('pesan', sa.Text(), nullable=True),
    sa.Column('jumlah_record', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['pengguna.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('satuan_pendidikan',
    sa.Column('npsn', sa.String(length=8), nullable=False),
    sa.Column('nama_sekolah', sa.String(length=200), nullable=False),
    sa.Column('alamat_lengkap', sa.Text(), nullable=True),
    sa.Column('jenjang_pendidikan', sa.Enum('PAUD', 'SD', 'SMP', 'SMA', 'SMK', name='jenjangenum'), nullable=False),
    sa.Column('status_sekolah', sa.Enum('Negeri', 'Swasta', name='statussekolahenum'), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('akreditasi', sa.String(length=5), nullable=True),
    sa.Column('wilayah_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wilayah_id'], ['wilayah.wilayah_id'], ),
    sa.PrimaryKeyConstraint('npsn')
    )
    op.create_table('statistik_pendidikan',
    sa.Column('stat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('npsn', sa.String(length=8), nullable=False),
    sa.Column('tahun_ajaran', sa.String(length=9), nullable=False),
    sa.Column('semester', sa.Enum('Ganjil', 'Genap', name='semesterenum'), nullable=False),
    sa.Column('jumlah_siswa', sa.Integer(), nullable=False),
    sa.Column('jumlah_guru', sa.Integer(), nullable=False),
    sa.Column('jumlah_rombel', sa.Integer(), nullable=False),
    sa.Column('rasio_siswa_guru', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('rasio_siswa_rombel', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['npsn'], ['satuan_pendidikan.npsn'], ),
    sa.PrimaryKeyConstraint('stat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistik_pendidikan')
    op.drop_table('satuan_pendidikan')
    op.drop_table('log_sinkronisasi')
    op.drop_table('wilayah')
    op.drop_table('pengguna')
    # ### end Alembic commands ###
